defaults:
  - _self_

data:
  path: data/
  test_image: test_image.png
  extensions: ['.jpg', '.jpeg', '.png', '.bmp']
  max_display: 5

fractal:
  box_sizes: [2, 4, 8, 16, 32]
  min_black_ratio: 0.1
  
multifractal:
  q_values: [-5, -3, -1, 0, 1, 3, 5]
  enabled: false  # Set to false to disable

directional:
  angles: [0, 45, 90, 135]
  enabled: false  # Set to false to disable

stroke_analysis:
  enabled: false  # Set to false to disable

topological:
  enabled: false  # Set to false to disable

spatial:
  grid_size: 3
  enabled: false  # Set to false to disable

results:
  path: handwriting_features/
  output_file: fractal_analysis_results.csv

display:
  theme: monokai
  spinner: point
  verbosity: 0  # 0=minimal, 1=normal, 2=verbose