defaults:
  - _self_

data:
  path: data/
  db_info: Subject_db_personal_features.csv
  feat_folder: Feature_fractal

settings: 
  verbose: 0
  debug: True
  base_seed: 42
  n_runs: 1 
  full_reproducibility: True

preprocessing:
  scaler: Robust

feature_selection:
  enabled: True  
  method: "selectkbest"  
  k: 0.4  # Number of features to select (int) or proportion (float between 0 and 1)
  score_func: "mutual_info_classif"  # Scoring function: 'f_classif', 'chi2', 'mutual_info_classif'
  save_plots: True 

hyperparameter_tuning:
  models: ["lgbm"]  # Models: 'rf' for Random Forest, 'lgbm' for LightGBM, 'mlp' for Multi-layer Perceptron
  n_trials: 50  # Number of trials for Optuna
  cv: 3  
  metric: "accuracy"  # Metric to optimize: 'accuracy', 'f1', 'roc_auc'
  output_dir: "./results"  